dist: trusty
language: scala
scala:
- 2.12.8
jdk:
- oraclejdk8
script:
- sbt +test
before_deploy:
- pip install --user release-manager==0.4.1.rc2
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
  - secure: MB/gDxYfKkwW1QEo+YIphwldc3gPeY/DpoZ5JgP1p8nfiv521+Ii9eOtLrDR/P9+yQUWM/9+VEkNKHEVjiPPqmn7BpBfi8mj9AXh62uNSq4V0UdeGN+0e7YPNcz5/hfP5QpJoNgI1HgCY3hNVLbL4CAYjhiGTwTdo3pQINQ4ZmfJIW/0z5YuhxZH697HzlK0FQDIe7Yz4ZY4M7gBAfAUL4bttDtX+sDGBsDEtYY9BuqWDKngfRNehR6KKDVIyUApeFfsATwhJRcclswQFk9BaRWz6usP8xO1AOfio40BTELkaiMv2r1RkTNBXIE1pDbi3c4tAjsunC3VcwD1LxGxFHlwkPV4aGM3sjG/OBU//pYiNwQbcWdHWuN+iFhnBTL/1SexXCxmfQKb7bpiFUC7N+9wZB7t4sSatZtAHRRe5T2B7r/VQ7p8TeBWA7eiXDkTzcrjvTOpWiRuyOfvpjIqt9ZdhEwXJ+S1EpDYTZXvYH28PlasLPvqCgNreCUzQ9/GSbOvHENp5ihG45p9INaKwQZVf3ks7DcVUv1f8oCweOglojhOgWUuxqVDMzSakSpjLHeXzMvaQKaFLa4BGvtl2PSxATh8c/z+2itpMgqCNULnBg6mZMfa1SF5CpRyc5P/Ihuu9bi2x5P2mQM/IL37rCQjm56cbRq4+7ZZq1gPMVQ=
  - secure: paO6bUKwM+EdXisegw4m2VqkeiTrMaTfjaqGhEXToFBzRomnM+88qjixVK2VhfPdauV04BVWzXTn9G+QsJpb2wjx2p21hnqiLyXw2uuA01lxCU/AaX3Y9d0eLcNe52oQyBgB3u5l5eslSUWzFL/MwDktHY4/lzhOTJKCTH1FTZBp4p6XBLjxL3fYyV88VT507+iuUjGgXVPIryoA4e+71rc8qy+QbGrhYwfmYKWj9i3MO/2WXMmOdy8fF9zCe799vbAKrLKWg54Lgpkv6hsSfq/uC8Am6+M7ObwriXDPNpPvTcdbRq51QWb2W1bc1hyZr7Njz/gH7SOr4i9PXPlg362bGoBohdXtjXVlLL1Y91Nvn17xlEeTpW7i3yUrM9Nc7OzP/ZE1R2i3exvh7pat0GOJFUHLuow92f1S2KvyscdurzEnPt0kgCiAxH6VMo8P6YA5vlH5A3gqPtHjFskaMHVfJuXxNSggLYfABSrMx9elqtVQjJqNDueXnH7C1FgRUwolPz7A7btf/1QVSG0bMJXlNlW26IUZkiIRJR8OPYv0VxAdzuahAiCyrwB1IH8e88t4Mj/sa0dYOJXfvd9GrLUbPNfNPum7RODsWJKcioizaatb+EIBD8zQDMfY0+f/OPSIWdmYZxqWwR+etemtAm2HXp1i6amxzcyCwSVFWFk=
